[package]
name = "reshape-cli"
version.workspace = true
edition.workspace = true
default-run = "reshape"

[[bin]]
name = "reshape"
path = "src/main.rs"

[dependencies]
axum.workspace = true
clap.workspace = true
dirs.workspace = true
futures-util.workspace = true
reshape-core = { path = "../reshape-core" }
reshape-browser = { path = "../reshape-browser" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ts-rs.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
tokio-tungstenite.workspace = true
