[package]
name = "reshape-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
notify.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
ts-rs.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
